[package]
name = "crawler-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.7", features = ["blocking", "json"]}
scraper = "0.20.0"
tokio = {version = "1.39.3", features = ["full"]}